# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NcLAHn3af6eFwpYWWt_GtQNYzT_2Nkbh
"""

import pandas as pd
import numpy as np
import torch as th
import seaborn as sb
import matplotlib.pyplot as plt

import flask
from flask import Flask, render_template, request, redirect


from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from keras.utils import np_utils
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder 
from sklearn import datasets
from sklearn.cluster import KMeans
from sklearn.manifold import TSNE

import pickle

from numpy import array
from numpy import argmax
from keras.utils import to_categorical

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')



name_array = []
business_array = []
email_array = []
location_array = []


@app.route('/send', methods=['GET', 'POST'])
def send():

    if request.method == "POST":

        req = request.form
        # print(req)

        name = req.get("name")
        name_array.append(name)
        name_array[0] = name

        business = req.get("business")
        business_array.append(business)
        business_array[0] = business
    

        email = req.get("email")
        email_array.append(email)
        email_array[0] = email


        location = req.get("location")
        location_array.append(location)
        location_array[0] = location

        message = req.get("message")
        
        print(message)

        return redirect(request.url)

    return render_template('index.html')


# @app.route("/upload-image", methods=["GET", "POST"])
# def upload_image():

#     if request.method == "POST":

#         if request.files:

#             image = request.files["file_image"]

#             image.save(os.path.join(app.config["IMAGE_UPLOADS"], "" + email_array[0] + ".png"))

#             print(image)

#             return redirect(request.url)


#     print("[INFO] loading model...")
#     model = load_model(config.MODEL_PATH)

#     # grab the paths to the fire and non-fire images, respectively
#     print("[INFO] predicting...")
#     firePaths = list(paths.list_images(config.FIRE_PATH))
#     nonFirePaths = list(paths.list_images(config.SAMPLE_FIRE_PATH))


#     imagePaths = nonFirePaths
#     random.shuffle(imagePaths)
#     imagePaths = imagePaths[:config.SAMPLE_SIZE]

#     # loop over the sampled image paths
#     for (i, imagePath) in enumerate(imagePaths):
#         # load the image and clone it
#         image = cv2.imread(imagePath)
#         output = image.copy()

#         # resize the input image to be a fixed 128x128 pixels, ignoring
#         # aspect ratio
#         image = cv2.resize(image, (128, 128))
#         image = image.astype("float32") / 255.0
            
#         # make predictions on the image
#         preds = model.predict(np.expand_dims(image, axis=0))[0]
#         j = np.argmax(preds)
#         label = config.CLASSES[j]

#         # draw the activity on the output frame
#         # text = label if label == "Non-Fire" else "Fire"

#         if label == "Non-Fire":
#             text = "Non-Fire"

#         else:

#             text = "Fire"

#             yag = yagmail.SMTP('contact.firehawk@gmail.com', 'fire246810')
#             # contents = ["Latitude: " + lat_array[0] + "\nLongitude: " + longitude_array[0] + "\nDescription: " + description_array[0], '/Users/samarth/Downloads/Flexor/static/result_img/' + email_array[0] + '.png']
#             contents = ["Latitude: " + lat_array[0] + "\nLongitude: " + longitude_array[0] + "\nDescription: " + description_array[0], '~firehawk/public_html/static/result_img' + email_array[0] + '.png']
#             yag.send('contact.firehawk@gmail.com', email_array[0], contents)
#             yag.send(email_array[0], "Confirmation Email", "We will be processing your form!")

#             # i = i + 1

#             # email_array.clear()
#             # description_array.clear()
#             # lat_array.clear()
#             # longitude_array.clear()


#         output = imutils.resize(output, width=500)
#         cv2.putText(output, text, (35, 50), cv2.FONT_HERSHEY_SIMPLEX,
#             1.25, (0, 255, 0), 5)

#         # write the output image to disk	 
#         filename = "{}.png".format(i)
#         # filename = "" + output + ".png".format(i)
#         p = os.path.sep.join([config.OUTPUT_IMAGE_PATH, filename])
#         cv2.imwrite(p, output)

#     return render_template("index.html")



if __name__ == "__main__":
    app.debug = True
    app.run()
